<# Run: powershell -STA -ExecutionPolicy Bypass -File .\Scan-FiveMClient.ps1 -Endpoint https://your-host/reports #>
[CmdletBinding()]param([string]$Endpoint='https://audit.example.com/reports')
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop'
function Invoke-Audit($code,[scriptblock]$progress){
 $roots=@(@((Join-Path $env:LOCALAPPDATA 'FiveM'),(Join-Path $env:APPDATA 'CitizenFX'),(Join-Path $env:LOCALAPPDATA 'DigitalEntitlements'),(Join-Path $env:ProgramFiles 'Rockstar Games'),(Join-Path ceholderText='PIN (ABCD-1234)';$pin.CharacterCasing='Upper'
$ok=New-Object Windows.Forms.CheckBox;$ok.Text='I understand and consent to this audit and report submission.';$ok.Location='22,180';$ok.AutoSize=$true
$status=New-Object Windows.Forms.Label;$status.Text='Enter the PIN shown in game.';$status.Location='22,215';$status.Size='490,24';$bar=New-Object Windows.Forms.ProgressBar;$bar.Location='22,242';$bar.Size='490,18';$go=New-Object Windows.Forms.Button;$go.Text='Start scan';$go.Location='390,278';$go.Size='122,30'
$go.Add_Click({if($pin.Text-notmatch'^[A-Z0-9]{4}-[A-Z0-9]{4}$'){[Windows.Forms.MessageBox]::Show('Enter a valid PIN.');return};if(-not$ok.Checked){[Windows.Forms.MessageBox]::Show('Consent is required.');return};$go.Enabled=$false;try{$r=Invoke-Audit $pin.Text {param($text,$pct)$status.Text=$text;$bar.Value=$pct;[Windows.Forms.Application]::DoEvents()};$status.Text='Submitting report…';$bar.Value=95;[Windows.Forms.Application]::DoEvents();$u=[Uri]$Endpoint;if($u.Scheme-ne'https'-and$u.Host-notin@('localhost','127.0.0.1')){throw'Remote endpoints must use HTTPS.'};Invoke-RestMethod -Method Post -Uri $Endpoint -ContentType'application/json'-Body($r|ConvertTo-Json -Depth 6)|Out-Null;$bar.Value=100;$status.Text='Complete. You may close this window.'}catch{$status.Text='Scan failed.';[Windows.Forms.MessageBox]::Show($_.Exception.Message,'FiveM Audit Scanner')}finally{$go.Enabled=$true}})
$f.Controls.AddRange(@($title,$info,$pin,$ok,$status,$bar,$go));[void]$f.ShowDialog()
